### PR TITLE
Added two sentences to charter document further highlighting that no …

### PR DESCRIPTION
**Pull request by matthewcbyington**
Added two sentences to charter document further highlighting that no key material is actually transffered. Making this commit primarily to address Michael's feedback from the SECRET email distribution."
[charter-clarification-feb22 19b5b2c] Added two sentences to charter document further highlighting that no key material is actually transffered. Making this commit primarily to address Michael's feedback from the SECRET email distribution.

### CODE REVIEW

**Comment by matthewcbyington** [comment]
@nicksha we are reviewing this internally but if y'all could take a look at what I wrote and see if it makes sense. This is primarily from the discussion with Michael and others on the SECRET distribution email list to try to clarify.

**Comment by nicksha** [comment]
LGTM.

The "credential" part has always created misunderstanding, thanks for clarifying further.

**Comment by matthewcbyington** [comment]
> LGTM.
> 
> The "credential" part has always created misunderstanding, thanks for clarifying further.

Thanks Nick. Just going to wait a bit so others see it and see how they feel before merging but feedback looks good so far on the change as well.

**Comment by matthewcbyington** [comment]
Merging this now

**Review by alexpell00 — COMMENTED** [review]
LGTM!

**Pull request merged**
